apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: realworldbackend
  name: realworldbackend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realworldbackend
  template:
    metadata:
      labels:
        app: realworldbackend
    spec:
      containers:
        - image: 'nginx:latest'
          name: realworldbackend
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
  name: backend
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: realworldbackend
  type: LoadBalancer
